[font]
normal = { family = "JetBrains Mono"}
size = 14

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
