#!/bin/bash

WORKFLOWS_DIR=$HOME/tasker_workflows


function die() {
    echo $1
    exit $2
}

function usage() {
    echo "tasker [COMMAND] [OPTIONS...]

COMMANDS
    - list               Lists all the available workflows.
        $ tasker list
        
    - start|run|execute  Starts a workflow.
        $ tasker start \"workflow\"

    - usage              Displays this message
        $ tasker usage
"
}

function start-command() {
    if [ ! -f "$WORKFLOWS_DIR/$1" ]; then
        die "Couldn't find a workflow named as '$1'" 3
    fi

    "$WORKFLOWS_DIR/$1"
}

function list-command() {
    echo "Available workflows:"
    for workflow in $WORKFLOWS_DIR/*; do
        if [ -f $workflow ]; then
            echo " - $workflow"
        fi
    done
}

if [ ! -d $WORKFLOWS_DIR ]; then
    die "The workflows directory doesn't exist ($WORKFLOWS_DIR)." 1
fi

if [ $# -lt 1 ]; then
    usage
    die "Not enough arguments" 1
fi

case $1 in
    "usage" | "help")
        usage
        ;;

    "start" | "run" | "execute")
        if [ $# -lt 2 ]; then
            usage
            die "Not enough arguments" 2
        fi
        start-command $2
        ;;
    
    "list")
        list-command
        ;;

    *)
        usage 
        die "Unknown command '$1' " 1
        ;;
esac


